[package]
name = "inbox"
version = "1.0.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
solana-program = "2.2.1"
borsh = { version = "1.5.4", features = ["derive"] }
libsecp256k1 = "0.7.1"

[package.metadata.solana]
features = ["disable-audit"]
