[features]
seeds = false
skip-lint = false
[programs.localnet]
anchor_inbox = "CVphDNHfy46bkV3zf3jajy9HF48osy2j7NsbA4aWxwFw"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/dante/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
